package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();
    List<Cart> selectAllByUserid(@Param("userid") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);

    Cart findCartByProductId(@Param("productId") Integer productId);

    int updateByProductId(@Param("productId")Integer productId,@Param("count") Integer count);
   /**
    * 统计购物车中未被选中的商品数量
    * */
    int  unCheckedCount(@Param("userId")Integer userId);


    int updateCheckedByUserId(@Param("userId")Integer userId,@Param("check") Integer check);

    int updateCheckedByUserIdAndProductId(@Param("userId")Integer userId,
                                          @Param("productId")Integer productId,
                                          @Param("check") Integer check);


   int  findCheckByProductId(@Param("productId")Integer productId,@Param("userId") Integer userId);

    List<Cart> findCartByUserIdAndChecked(@Param("userId")Integer userId);

    int deleteByIds(@Param("idList") List<Integer> ids);

}